### ISSUE TITLE
[Crash] interface conversion 

### ISSUE THREAD

**Issue by SegFault42** [deletescape/goop#12]
Hi !

I'm got a crash when i'm running the tool.
I'm not familiar with interfaces in golang and I cant debug it.

Can you take a look please 

panic: interface conversion: jobtracker.Context is *workers.RecursiveDownloadContext, not workers.RecursiveDownloadContext

goroutine 25 [running]:
github.com/deletescape/goop/internal/workers.RecursiveDownloadWorker(0xc0000c81c0, 0xc0000b41b0, 0xa, 0x14e3700, 0xc0000af5f0)
	/Users/segfault42/Documents/goop/internal/workers/recursivedownload.go:22 +0xf49
github.com/deletescape/jobtracker.workRoutine(0xc0000c81c0, 0x15c5470, 0x14e3700, 0xc0000af5f0)
	/Users/segfault42/go/pkg/mod/github.com/deletescape/jobtracker@v0.0.0-20211024175651-68fbc3d60d80/jobtracker.go:132 +0x92
created by github.com/deletescape/jobtracker.(*JobTracker).StartAndWait
	/Users/segfault42/go/pkg/mod/github.com/deletescape/jobtracker@v0.0.0-20211024175651-68fbc3d60d80/jobtracker.go:74 +0x85

**Comment by deletescape** [comment]
this should be fixed now
