### ISSUE TITLE
go get does nothing

### ISSUE THREAD

**Issue by c0d3z3r0** [deletescape/goop#2]
No idea what's wrong here, but `go get -u github.com/deletescape/goop` hangs... Other projects like https://github.com/deletescape/sloot work just fine.

Oh lol, while writing this, I got an output, but still no binary in go/bin:

~~~
go get -u github.com/deletescape/goop

code in directory /home/c0d3/go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"
~~~

Disclaimer: non-go guy here ;)

**Comment by deletescape** [comment]
huh thats odd, i dont think i've seen that before, but i'll try to figure it out on my second device

**Comment by deletescape** [comment]
it should work if you run it with

```
GO111MODULE=on go get -u github.com/deletescape/goop
```

**Comment by c0d3z3r0** [comment]
lol. indeed, worked fine

**Comment by nchiarappa** [comment]
![image](https://user-images.githubusercontent.com/29224695/100753445-0f7ac500-33ea-11eb-844c-9d5955cdb95e.png)

Hello! It seems the issue still persists with the new command with GO111MODULE=on. Any suggestion?

Ty
